#pragma once
#include "../ui/asciiart.h"

// Generated by assets/gen_cat_ascii.py - do not hand-edit.
// Dense 40x30 ASCII animation of a cat face, sized for the built-in
// 6x8 font on a 240x240 panel (one character per cell).
//
// The expression sets are short and meant to be played once, in step
// with a named animation, not looped like the idle frames.

namespace assets {

extern const asciiart::Frame CAT_ASCII[];
extern const int CAT_ASCII_COUNT;
extern const asciiart::Frame CAT_ASCII_SLEEP[];
extern const int CAT_ASCII_SLEEP_COUNT;
extern const asciiart::Frame CAT_WINK[];
extern const int CAT_WINK_COUNT;
extern const asciiart::Frame CAT_SURPRISED[];
extern const int CAT_SURPRISED_COUNT;
extern const asciiart::Frame CAT_HAPPY[];
extern const int CAT_HAPPY_COUNT;
extern const asciiart::Frame CAT_ANGRY[];
extern const int CAT_ANGRY_COUNT;

}
