#pragma once
#include "../ui/asciiart.h"

// Generated by assets/gen_cat_ascii.py — do not hand-edit.
// Dense 40x30 ASCII animation of a cat face, sized for the built-in 6x8
// font on a 240x240 panel (one character per cell, exactly filling it).
namespace assets {

extern const asciiart::Frame CAT_ASCII[];
extern const int CAT_ASCII_COUNT;
extern const asciiart::Frame CAT_ASCII_SLEEP[];
extern const int CAT_ASCII_SLEEP_COUNT;

}
