#pragma once
#include "../ui/asciiart.h"

// Generated by assets/gen_creature.py - do not hand-edit.
// Dense 40x30 ASCII animation, sized for the built-in
// 6x8 font on a 240x240 panel (one character per cell).
//
// The expression sets are short and meant to be played once, in step
// with a named animation, not looped like the idle frames.

namespace assets {

extern const asciiart::Frame FOX_ASCII[];
extern const int FOX_ASCII_COUNT;
extern const asciiart::Frame FOX_ASCII_SLEEP[];
extern const int FOX_ASCII_SLEEP_COUNT;
extern const asciiart::Frame FOX_WINK[];
extern const int FOX_WINK_COUNT;
extern const asciiart::Frame FOX_SURPRISED[];
extern const int FOX_SURPRISED_COUNT;
extern const asciiart::Frame FOX_HAPPY[];
extern const int FOX_HAPPY_COUNT;
extern const asciiart::Frame FOX_ANGRY[];
extern const int FOX_ANGRY_COUNT;

}
