#pragma once
#include "../ui/asciiart.h"

// Generated by assets/gen_from_image.py - do not hand-edit.
// Tire d'une photo detouree, pas d'un dessin parametrique.

namespace assets {

extern const asciiart::Frame FOXPHOTO_ASCII[];
extern const int FOXPHOTO_ASCII_COUNT;
extern const asciiart::Frame FOXPHOTO_ASCII_SLEEP[];
extern const int FOXPHOTO_ASCII_SLEEP_COUNT;
extern const asciiart::Frame FOXPHOTO_WINK[];
extern const int FOXPHOTO_WINK_COUNT;
extern const asciiart::Frame FOXPHOTO_SURPRISED[];
extern const int FOXPHOTO_SURPRISED_COUNT;
extern const asciiart::Frame FOXPHOTO_HAPPY[];
extern const int FOXPHOTO_HAPPY_COUNT;
extern const asciiart::Frame FOXPHOTO_ANGRY[];
extern const int FOXPHOTO_ANGRY_COUNT;

}
